_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    NORM: GN
  BACKBONE:
    FREEZE_AT: 1
    NAME: build_resnet_backbone
  ROI_HEADS:
    NUM_CLASSES: 5
    NMS_THRESH_TEST: 0.3
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TEST: 300
  
INPUT:
  MIN_SIZE_TRAIN: (900,)
  MIN_SIZE_TEST: 1200
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2007_trainval')
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 100
  BASE_LR: 0.00125
  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 2

OUTPUT_DIR: ./output_GN_64_no_aug